import './globals.css'
import { AuthProvider } from './AuthContext';

import Nav from './components/Nav';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Route Planner',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <AuthProvider>
    <html lang="en">
      <body>
        <main className="app">
          <Nav />
        </main>
        {children}
      </body>

     {/* <body>{children}</body> */}
    </html>
    </AuthProvider>
  )
}
