import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@components/Nav';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Route Planner',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <main className="app">
          <Nav />
        </main>
        {children}</body>
    </html>
  )
}
